server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/route_planner
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

route:
  find:
    url: http://localhost:15002/api/v1/mock/route